language: node_js
node_js:
  - "node"
branches:
  only:
  - master
  - release
before_install:
  - eval "$(ssh-agent -s)"
  - echo ${PRIVATE} > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-add ~/.ssh/id_rsa
deploy:
  - provider: script
    skip_cleanup: true
    script: bash .travis/deploy.sh production
    on:
      branch: master
