language: node_js
node_js:
- node
branches:
  only:
  - master
  - release
before_install:
- openssl aes-256-cbc -K $encrypted_4ba095432ca3_key -iv $encrypted_4ba095432ca3_iv
  -in .travis/id_rsa.enc -out .travis/id_rsa -d
- eval "$(ssh-agent -s)"
- cp .travis/id_rsa > ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- ssh-add ~/.ssh/id_rsa
deploy:
- provider: script
  skip_cleanup: true
  script: bash .travis/deploy.sh production
  on:
    branch: master
